3dfermi-chemial: 3dfermi-chemial.o
	g++ 3dfermi-chemial.o -o 3dfermi-chemial -std=gnu++11

3dfermi-chemial.o: 3dfermi-chemial.cpp
	g++ -c 3dfermi-chemial.cpp -std=gnu++11 -O3

clean:
	rm -f *.o 